#!/bin/sh

# This hackish script copies the necessary library files into the Maple IDE
# repository.

# Change this
DEST=`pwd`/../maple-ide/hardware/leaflabs/cores/maple/

ARCH=`uname -a`

FILES="libmaple/adc.c
    libmaple/adc.h
    libmaple/bootVect.h
    libmaple/exc.c
    libmaple/exti.c
    libmaple/exti.h
    libmaple/flash.c
    libmaple/flash.h
    libmaple/gpio.c
    libmaple/gpio.h
    libmaple/libmaple.h
    libmaple/libmaple_types.h
    libmaple/nvic.c
    libmaple/nvic.h
    libmaple/rcc.c
    libmaple/rcc.h
    libmaple/syscalls.c
    libmaple/systick.c
    libmaple/systick.h
    libmaple/timers.c
    libmaple/timers.h
    libmaple/usart.c
    libmaple/usart.h
    libmaple/usb.c
    libmaple/usb.h
    libmaple/usb_regs.h
    libmaple/util.c
    libmaple/util.h
    core/binary.h
    core/bits.h
    core/ext_interrupts.c
    core/ext_interrupts.h
    core/io.h
    core/main.cxx
    core/Print.cpp
    core/Print.h
    core/pwm.c
    core/pwm.h
    core/time.c
    core/time.h
    core/wiring_analog.c
    core/wiring.c
    core/wiring_digital.c
    core/wiring.h
    core/wiring_math.cpp
    core/wiring_math.h
    core/wiring_shift.c
    core/WProgram.h
    core/comm/HardwareSerial.cpp
    core/comm/HardwareSerial.h
    core/comm/HardwareUsb.cpp
    core/comm/HardwareUsb.h"

# First see if this folder exists
if !(test -d $DEST/lanchon-stm32)
then
    mkdir $DEST/lanchon-stm32
fi

# Then copy over linker files
cp -v stm32conf/* $DEST
cp -v stm32conf/lanchon-stm32/* $DEST/lanchon-stm32

# Finally the source files
cp -v $FILES $DEST

