#!/bin/sh

# This hackish script copies the necessary library files into the Maple IDE
# repository.

# Change this
DEST=`pwd`/../maple-ide/hardware/leaflabs/cores/maple/

ARCH=`uname -a`

FILES="LICENSE
    ./libmaple/*.h
    ./libmaple/*.c
    ./libmaple/usb/*.h
    ./libmaple/usb/*.c
    ./libmaple/usb/usb_lib/*.h
    ./libmaple/usb/usb_lib/*.c
    ./wirish/*.h
    ./wirish/*.c
    ./wirish/main.cxx
    ./wirish/*.cpp
    ./wirish/comm/*.cpp
    ./wirish/comm/*.h
    ./support/ld/maple/
    ./support/ld/maple_native/
    ./support/ld/libcs3-lanchon-stm32.a
    ./support/ld/names.inc"


echo "First make sure DEST exists: $DEST"
if !(test -d $DEST)
then
    echo "Nope! Make sure you're doing this right?"
    exit -1
fi

echo "Then delete the old files..."
rm -r $DEST/*.c $DEST/*.cpp $DEST/*.h $DEST/*.cxx $DEST/*.ld $DEST/*.inc $DEST/*.a $DEST/maple/ $DEST/maple_native/

echo "Finally copy the new source files!"
cp -r $FILES $DEST
echo "Done."
